2025-10-03 12:18:11.448 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.449 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.449 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
2025-10-03 12:18:11.450 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
aiodns.error.DNSError: (4, 'Domain name not found')
